### ISSUE TITLE
Parse Error

### ISSUE THREAD

**Issue by felipebritor** [dbtek/react-popover#3]
Hello,

It might be something ridiculous, but I'm getting a strange error trying to use react-popover:

<img width="830" alt="screen shot 2017-03-29 at 13 48 45" src="https://cloud.githubusercontent.com/assets/9297662/24466273/b0d8cd2a-1486-11e7-9c29-87ef8538f381.png">

I'm using webpack with babel-loader and the following presets: ['es2015', 'react']

Thanks in advance

**Comment by mm-rp** [comment]
@felipebritor were you ever able to resolve this? Getting the same error

**Comment by dbtek** [comment]
Hi all,

Sorry for the trouble. I couldn't have time to release a fix for this and #2. Should be resoved with v0.2.0.
