### ISSUE TITLE
Node is undefined

### ISSUE THREAD

**Issue by amiral84** [dbtek/react-popover#9]
I updated to latest version (v. `0.2.2`) of this component and it doesn't work. I get following error: `Node is undefined` at line 120 of `Popover.js`. Can you check and make the fix?

**Comment by mahdt** [comment]
having the same issue when I run tests using mocha

**Comment by nandukalidindi** [comment]
This happens in all the Webpack bundled applications probably due to the loss of global context. I issued a pull request with a possible fix for the time being https://github.com/dbtek/react-popover/pull/10. Please review or add your comments to it.
